### ISSUE TITLE
xterm directory empty

### ISSUE THREAD

**Issue by s1037989** [Prajithp/mojo-terminal#1]
If you can't include the xterm files, document in README how to do.
$ git clone git@github.com:sourcelair/xterm.js.git
$ cp -a xterm.js/dist/* mojo-terminal/public
$ cp xterm.js/demo/style.css mojo-terminal/public

Love that you made this Mojolicious project, BTW!  It's fantastic!!

**Comment by Prajithp** [comment]
fixed now. Thanks :)
